codecov:
  require_ci_to_pass: yes

coverage:
  range: 99.999...100
  status:
    project:
      default:
        target: 100%
        threshold: 0%
    patch:
      default:
        target: 100%
        threshold: 0%
