language: php

php:
  - 5.6
  - 7.0
  - 7.1

dist: trusty

env:
  global:
    - PHPUNIT=1

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: COVERAGE=1 PHPUNIT=0

    - php: 7.0
      env: PHPSTAN=1 PHPUNIT=0

    - php: 7.1
      env: PHPSTAN=1 PHPUNIT=0

before_install:
  - if [ $COVERAGE != 1 ]; then phpenv config-rm xdebug.ini; fi

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - if [[ $COVERAGE = 1 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi
  - if [[ $PHPUNIT = 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPSTAN = 1 ]]; then vendor/bin/phpstan analyse -l 4 -c phpstan.neon src; fi

after_success:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi